-- 002_update_dispositions_and_facilities.sql
-- Create or Update Facilities and Dispositions tables according to Requirement Document 2

CREATE TABLE IF NOT EXISTS public.facilities (
    id BIGSERIAL PRIMARY KEY,
    facility_key TEXT UNIQUE NOT NULL,
    seq INT,
    facility_type TEXT,
    compliance_status TEXT,
    investigation_status TEXT,
    facility_name TEXT,
    jibun_address TEXT,
    road_address TEXT,
    hangjeong_dong TEXT,
    building_register_total_parking INT DEFAULT 0,
    bylaw_total_parking INT DEFAULT 0,
    building_permit_date TEXT,
    use_approval_date TEXT,
    building_age_type TEXT,
    public_lh_type TEXT,
    public_general_type TEXT,
    parking_required_cnt INT DEFAULT 0,
    parking_installed_cnt INT DEFAULT 0,
    parking_above_ground_cnt INT DEFAULT 0,
    parking_underground_cnt INT DEFAULT 0,
    parking_uninstalled_cnt INT DEFAULT 0,
    parking_compliance_status TEXT,
    charger_required_cnt INT DEFAULT 0,
    charger_fast_req_cnt INT DEFAULT 0,
    charger_installed_total INT DEFAULT 0,
    charger_fast_cnt INT DEFAULT 0,
    charger_slow_cnt INT DEFAULT 0,
    charger_uninstalled_cnt INT DEFAULT 0,
    charger_compliance_status TEXT,
    total_household_cnt INT DEFAULT 0,
    ev_registered_cnt INT DEFAULT 0,
    charger_reported TEXT,
    insurance_joined TEXT,
    parallel_parking_op TEXT,
    parallel_parking_cnt INT DEFAULT 0,
    fire_manual_dist TEXT,
    manager_name_encrypted TEXT,
    new_contact_encrypted TEXT,
    existing_contact_encrypted TEXT,
    investigation_1st TEXT,
    investigation_date_1 TEXT,
    investigator_1 TEXT,
    check_item_1 TEXT,
    action_plan_1 TEXT,
    remarks_1 TEXT,
    investigation_2nd TEXT,
    investigation_date_2 TEXT,
    investigator_2 TEXT,
    check_item_2 TEXT,
    action_plan_2 TEXT,
    remarks_2 TEXT,
    investigation_3rd TEXT,
    investigation_date_3 TEXT,
    investigator_3 TEXT,
    check_item_3 TEXT,
    action_plan_3 TEXT,
    remarks_3 TEXT,
    investigation_4th TEXT,
    investigation_date_4 TEXT,
    investigator_4 TEXT,
    check_item_4 TEXT,
    action_plan_4 TEXT,
    remarks_4 TEXT,
    investigation_5th TEXT,
    investigation_date_5 TEXT,
    investigator_5 TEXT,
    check_item_5 TEXT,
    action_plan_5 TEXT,
    remarks_5 TEXT,
    final_conclusion TEXT,
    management_body TEXT,
    job25_total_parking INT DEFAULT 0,
    correction_order_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Drop old dispositions table if exists and recreate with new schema
DROP TABLE IF EXISTS public.dispositions CASCADE;

CREATE TABLE public.dispositions (
    id BIGSERIAL PRIMARY KEY,
    facility_key TEXT NOT NULL,
    seq INT,
    current_status TEXT,
    facility_name TEXT,
    facility_address TEXT,
    target_type TEXT, -- '시설', '소유자', '관리자' 등
    owner_name TEXT,
    target_category TEXT, -- '부지/건물', '시설' 등
    advance_notice_target TEXT, -- 'O' / 'X'
    advance_notice_date TEXT,
    advance_notice_method TEXT,
    postal_road_address TEXT,
    zipcode TEXT,
    send_date TEXT,
    return_status TEXT,
    copy_address_send_date TEXT,
    copy_address TEXT,
    copy_address_return TEXT,
    notice_publication TEXT,
    notice_pub_period TEXT,
    opinion_submitted TEXT,
    opinion_submit_date TEXT,
    opinion_content TEXT,
    correction_order TEXT,
    correction_order_date TEXT,
    correction_target TEXT,
    correction_reason TEXT,
    correction_period TEXT,
    correction_method TEXT,
    correction_return TEXT,
    correction_publication TEXT,
    corporate_num_encrypted TEXT,
    recipient_name_encrypted TEXT,
    building_register_total_parking INT DEFAULT 0,
    bylaw_total_parking INT DEFAULT 0,
    building_permit_date TEXT,
    use_approval_date TEXT,
    building_age_type TEXT,
    public_lh_type TEXT,
    public_general_type TEXT,
    parking_required_cnt INT DEFAULT 0,
    parking_installed_cnt INT DEFAULT 0,
    parking_above_ground_cnt INT DEFAULT 0,
    parking_underground_cnt INT DEFAULT 0,
    parking_uninstalled_cnt INT DEFAULT 0,
    parking_compliance_status TEXT,
    charger_required_cnt INT DEFAULT 0,
    charger_fast_req_cnt INT DEFAULT 0,
    charger_installed_total INT DEFAULT 0,
    charger_fast_cnt INT DEFAULT 0,
    charger_slow_cnt INT DEFAULT 0,
    charger_uninstalled_cnt INT DEFAULT 0,
    charger_compliance_status TEXT,
    facility_category TEXT,
    mandatory_install_compliance TEXT,
    contact_encrypted TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dispositions_facility_key ON public.dispositions(facility_key);
CREATE INDEX IF NOT EXISTS idx_dispositions_seq ON public.dispositions(seq);
